#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
. build/envsetup.sh
sed -i "s/wulan17/TimR/" kernel/xiaomi/mt6765/arch/arm/configs/cereus_defconfig 
. build/envsetup.sh
export VANILLA_BUILD=true
lunch pixys_cereus-userdebug
export SELINUX_IGNORE_NEVERALLOWS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	make pixys -j20
       # make aex -j20 #aosp extended
	zip=$(up out/target/product/cereus/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 5d && echo "ROM BUILD COMPLETED"
