#!/bin/bash
export VANILLA_BUILD=TRUE
MANIFEST=git://github.com/AOSPK/manifest.git
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name EinTim
git config --global user.email endme23@protonmail.com

git clone https://github.com/EinTim23/local_manifests -b r .repo/local_manifests

repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j4
 
