#!/bin/bash

MANIFEST=git://github.com/Evolution-X/manifest.git
BRANCH=elle

mkdir -p /tmp/rom
cd /tmp/rom

repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name EinTim
git config --global user.email endme23@protonmail.com

git clone https://github.com/EinTim23/local_manifests -b r .repo/local_manifests

repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
 
